### ISSUE TITLE
Actor Spawn feature hangs in many scenes

### ISSUE THREAD

**Issue by SSM240** [zsrtp/tpgz#87]
As per title, trying to use the Actor Spawn feature hangs the game in many scenes that I've tested.

I've hardly been exhaustive, but from my testing, here are some examples:
- Work fine: Upper Zora's River, Lanayru Main Field, Faron Spring, Ordon Village, Morpheel's room
- Hangs: Kakariko Village, Kakariko Graveyard, Eldin Main Field, Fishing Pond, Grotto 1

It's worth mentioning that my results haven't been _completely_ consistent - every so often it'll hang in a "working" scene or mysteriously work fine in a "broken" scene. But I'd say at least 90% of the time this is the behavior I see.

There doesn't seem to be much/any correlation between the complexity or size of the scene and how likely it is to work. It also doesn't matter what actor I select as long as it's not an invisible trigger or something (a good arbitrary example that demonstrates the problem is `[0031] <tree>`).

I'm testing this on Dolphin (`2409-30`), with an NTSC-U GC ROM (`GZ2E01`) and tpgz 1.0. If there's any other info I can provide, please let me know.

**Comment by Pheenoh** [comment]
Fixed in #86

**Comment by SSM240** [comment]
The 1.1.0 release doesn't work when I try to patch my ROM (NTSC-U GCN). I'm pretty sure it's not user error or a problem with my ROM, since the 1.0.0 release works fine.

![image](https://github.com/user-attachments/assets/0da444b0-352b-4f76-ac44-90c02d13f397)

**Comment by SSM240** [comment]
Alright, it turns out the web patcher does work (I'm not sure if the version wasn't there yesterday or I just didn't see it since it was at the bottom of the list), but more to the point, the bug doesn't actually seem to be fixed in 1.1.0, it's still hanging in most of the same locations as before. It's even having problems in Lanayru Main Field now, which previously worked fairly consistently, though the other locations I listed in the original post still seem to work.
